[server]
headless = true
port = 8501
enableCORS = true

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f0f0"
textColor = "#000000"
font = "sans serif"

[browser]
gatherUsageStats = false

[layout]
wideMode = false